blank_issues_enabled: false
contact_links:
  - name: Get help in GitHub Discussions ðŸ—£
    url: https://github.com/orgs/dita-ot/discussions
    about: Have a question? Not sure if your issue affects everyone? Ask the community in DITA-OT GitHub Discussions!
